### ISSUE TITLE
Google social sign is broken for newer Google projects

### ISSUE THREAD

**Issue by aiham** [openanalytics/containerproxy#37]
Currently containerproxy depends on an out of date version of `spring-social-google`: 1.0.0.RELEASE.

https://github.com/openanalytics/containerproxy/blob/9d8295a2015ea5cdb1b0e9d05ec9cf4e0bd25e74/pom.xml#L157-L159

The current version is [1.1.3](https://github.com/spring-social/spring-social-google/releases/tag/1.1.3) with support for the newer API.

The package also seems to have a newer groupId: `com.github.spring-social` (rather than `org.springframework.social`)

Here is information on the old API: https://developers.google.com/people/legacy

Because the old API is used I get a 403 error when Google redirects authenticated users back to shinyproxy:

```
2020-06-27 17:17:49.295  WARN 17745 --- [  XNIO-2 task-8] o.s.social.connect.web.ConnectSupport    : HttpClientErrorException while completing connection: 403 Forbidden
2020-06-27 17:17:49.296  WARN 17745 --- [  XNIO-2 task-8] o.s.social.connect.web.ConnectSupport    :       Response body: {
  "error": {
    "code": 403,
    "message": "Legacy People API has not been used in project 123456789 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/legacypeople.googleapis.com/overview?project=123456789 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.Help",
        "links": [
          {
            "description": "Google developers console API activation",
            "url": "https://console.developers.google.com/apis/api/legacypeople.googleapis.com/overview?project=123456789"
          }
        ]
      }
    ]
  }
}

2020-06-27 17:17:49.304 ERROR 17745 --- [  XNIO-2 task-8] o.s.s.c.web.ProviderSignInController     : Exception while completing OAuth 2 connection:

org.springframework.web.client.HttpClientErrorException: 403 Forbidden
     at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:94) ~[spring-web-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
     at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:79) ~[spring-web-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
     at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
     at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:777) ~[spring-web-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
     at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:730) ~[spring-web-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
     at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:686) ~[spring-web-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
     at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:334) ~[spring-web-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
     at org.springframework.social.google.api.impl.AbstractGoogleApiOperations.getEntity(AbstractGoogleApiOperations.java:50) ~[spring-social-google-1.0.0.RELEASE.jar!/:1.0.0.RELEASE]
     at org.springframework.social.google.api.plus.impl.PlusTemplate.getPerson(PlusTemplate.java:105) ~[spring-social-google-1.0.0.RELEASE.jar!/:1.0.0.RELEASE]
     at org.springframework.social.google.api.plus.impl.PlusTemplate.getGoogleProfile(PlusTemplate.java:110) ~[spring-social-google-1.0.0.RELEASE.jar!/:1.0.0.RELEASE]
     at org.springframework.social.google.connect.GoogleAdapter.fetchUserProfile(GoogleAdapter.java:51) ~[spring-social-google-1.0.0.RELEASE.jar!/:1.0.0.RELEASE]
     at org.springframework.social.google.connect.GoogleAdapter.fetchUserProfile(GoogleAdapter.java:31) ~[spring-social-google-1.0.0.RELEASE.jar!/:1.0.0.RELEASE]
     at org.springframework.social.google.connect.GoogleConnectionFactory.extractProviderUserId(GoogleConnectionFactory.java:37) ~[spring-social-google-1.0.0.RELEASE.jar!/:1.0.0.RELEASE]
     at org.springframework.social.connect.support.OAuth2ConnectionFactory.createConnection(OAuth2ConnectionFactory.java:93) ~[spring-social-core-1.1.6.RELEASE.jar!/:1.1.6.RELEASE]
     at org.springframework.social.connect.web.ConnectSupport.completeConnection(ConnectSupport.java:161) ~[spring-social-web-1.1.6.RELEASE.jar!/:1.1.6.RELEASE]
     at org.springframework.social.connect.web.ProviderSignInController.oauth2Callback(ProviderSignInController.java:228) ~[spring-social-web-1.1.6.RELEASE.jar!/:1.1.6.RELEASE]
```

**Comment by tverbeke** [comment]
Thanks @aiham Will be updated for the next release.

**Comment by LEDfan** [comment]
Hi @aiham 

Thank you for your investigation. We upgraded the google social dependency in the latest release (ContainerProxy 0.8.5 and ShinyProxy 2.4.0)

Feel free to re-open if you still encounter the issue.
